<program> ::=  <stmt_list> 
<stmt_list> ::= <stmt> <semi_col> | <stmt_list> <stmt> <semi_col>
<stmt> ::= <matched> | <unmatched> | <empty>
<stmt_block> ::= <l_cur> <stmt_list> <r_cur>


/* 1-) Identifier */
<ident_char> ::= <digit> | <letter> | <underscore>
<ident_char_list> ::= <ident_char_list> <ident_char> | <ident_char>
<identifier> ::= <letter> | <letter> <ident_char_list>


/* 2-) Assignment Statement */
<assignment_stmt> ::=  <identifier> <assign_op> <expr>

<constant> ::=  <int> | <char> | <string> | <boolean> | <double> | <list>
<constant_list> ::= <constant_list> <comma> <constant> | <constant> | <empty>
<list> ::= <l_sqr>  <constant_list> <r_sqr>

<boolean> ::= <true> | <false>
<double> ::= <number> . <number> | <sign> <number> . <number>
<int> ::= <number> | <sign> <number>

<character> ::= <digit> | <letter> | <underscore> | <symbol>
<char> ::= <char_identifier> <character> <char_identifier>
<char_list> ::= <char_list> <char> | <char>
<string> ::= <quote> <char_list> <quote>


/* 3-) and 4-) Expressions */
<expr> ::= <conditional_expr> 
<conditional_expr> ::= <comp_expr> <relational_op> <comp_expr> | <comp_expr>
<comp_expr> ::= <arithmetic_expr> <comparison_op> <arithmetic_expr> | <arithmetic_expr>


//  3-) Arithmetic expression definition includes precedence, associativity of the operators
<arithmetic_expr> ::= <arithmetic_expr> <add_op> <term> | <arithmetic_expr> <subs_op> <term> | <term>
<term> ::= <term> <mult_op> <factor> | <term> <div_op> <factor> | <term> <mod_op> <factor> | <factor>
<factor> ::= <expr> <base_op> <factor> | <result>
<result> ::= <l_p> <arithmetic_expr> <r_p> | <constant> | <identifier>


/* 5-) Loops */
<for_loop> ::= for <l_p> <assignment_stmt> ; <relational_expr> ; <arithmetic_expr> <r_p> <stmt_block>
<while_loop> ::= while <l_p> <expr> <r_p> <stmt_block>


/* 6-) Conditional statements */
<matched> ::= if <l_p> <logic_expr> <r_p> then <matched> else <matched>
            | <for_loop> | <while_loop> | <function_declaration> | <function_call>
            | <assignment_stmt> | <return_stmt> | <input_stmt> | <output_stmt>
<unmatched> ::= if <l_p> <logic_expr> <r_p> then <stmt_block>
              | if <l_p> <logic_expr> <r_p> then <matched> else <unmatched>


/* 7-) Statements for input/output */
<input_stmt> ::= <input_key> <l_p> <expr> <r_p>  
<output_stmt> ::= <output_key> <l_p> <expr> <r_p>


/* 8-) Function definition and function calls */
<function_declaration> ::= <function_key> <function_name> <l_p> <function_params> <r_p> <stmt_block>   
<function_call> ::= <function_name> <l_p> <function_params> <r_p>  
<return_stmt> ::= <return_key> <expr> 

<function_name> ::= <string>
<function_params> ::= <empty> | <function_param> | <function_params> , <function_param>
<function_param> ::= <identifier>


/* 9-) Comments */
<comment> ::= <slash> <slash> <string>


/* 10-) Primitive Functions */
<primitive_function_key> ::= readInclination | readAltitude
                            | readTemperature | readAcceleration
                            | turnOnCamera | turnOffCamera
                            | takePicture | readTimestamp

/* Miscellaneous */
<comma> ::= ,
<not_op> ::= !
<l_cur> ::= {
<r_cur> ::= }
<l_p> ::= (
<r_p> ::= )
<l_sqr> ::= [
<r_sqr> ::= ]
<return_key> ::= return
<function_key> ::= func
<begin_key> ::= begin
<end_key> ::= end
<input_key> ::= rin
<output_key> ::= rout
<empty> ::=
<add_op> ::= +
<subs_op> ::= -
<mult_op> ::= *
<div_op> ::= /
<mod_op> ::= %
<base_op> ::= **
<relational_op> ::= && | || | & | | 
<comparison_op> ::= == | != | >= | > | <= | <  
<assign_op> ::= =
<char_identifier> ::= '
<underscore> ::= _
<letter> ::= = a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|
               A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z
<symbol> ::= $ | ! | # | &
<digit> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<number> ::= <number> <digit> | <digit>
<slash> ::= /
<semicolumn> ::= ;
<sign> ::= + | -
<true> = true
<false> = false
