<program> ::=  <stmt_list> 
<stmt_list> ::= <stmt> <semi_col> | <stmt_list> <stmt> <semi_col>
<stmt> ::= <matched> | <unmatched> | <empty>
<stmt_block> ::= <l_cur> <stmt_list> <r_cur>

/* 1-) Identifier */
<identifier> ::= <letter> | <letter> <char_list>

/* 2-) Assignment Statement */
<assignment_stmt> ::=  <identifier> <assign_op> <expr> 
                     

<constant> ::=  <int> | <char> | <string> | <boolean> | <double> | <list>

<char> ::= <char_identifier> <digit> <char_identifier>
         | <char_identifier> <letter> <char_identifier>
         | <char_identifier> <symbol> <char_identifier>
<int> ::= <digit> | <sign> <digit> | <int> <digit>
<string> ::= <char_list>
<boolean> ::= <true> | <false>
<double> ::= // ToDo
<list> ::= // ToDo

/* 3-) and 4-) Expressions */
<expr> ::= <conditional_expr> 
<conditional_expr> ::= <comp_expr> <relational_op> <comp_expr> | <comp_expr>
<comp_expr> ::= <arithmetic_expr> <comparison_op> <arithmetic_expr> | <arithmetic_expr>

<relational_op> ::= && | || // add more
<comparison_op> ::= == | != | >= | > | <= | <  // add more if i missed

    //  3-) Arithmetic expression definition includes precedence, associativity of the operators
    <arithmetic_expr> ::= <arithmetic_expr> + <term> | <arithmetic_expr> - <term> | <term>
    <term> ::= <term> * <factor> | <term> / <factor> | <factor>
    <factor> ::= <expr> ** <factor> | <fact>
    <fact> ::= ( <arithmetic_expr> ) | <constant>

/* 5-) Loops */
<for_loop> ::= for ( <assignment_stmt> ; <relational_expr> ; <arithmetic_expr> ) <stmt_block>
<while_loop> ::= while ( <expr> ) <stmt_block>

/* 6-) Conditional statements */
<matched> ::= if ( <logic_expr> ) then <matched> else <matched>
            | <for_loop> | <while_loop> | <function_declaration> | <function_call>
            | <assignment_stmt> | <return_stmt>
<unmatched> ::= if ( <logic_expr> ) then <stmt_block>
              | if ( <logic_expr> ) then <matched> else <unmatched>

/* 7-) Statements for input/output */
// ToDo

/* 8-) Function definition and function calls */
<function_declaration> ::= <function_keyword> <function_name> ( <function_params> ) <stmt_block>
<function_call> ::= <function_name> ( <function_params> )

<function_keyword> ::= func
<function_name> ::= <string>
<function_params> ::= <empty> | <function_param> | <function_params> , <function_param>
<function_param> ::= <identifier>

/* 9-) Comments */
<comment> ::= <slash> <slash> <string>

/* Miscellaneous */
<not_op> ::= !
<l_cur> ::= {
<r_cur> ::= }
<begin_key> ::= begin
<end_key> ::= end
<empty> ::=
<assign_op> ::= =
<char_list> ::= <char_list> <char> | <char>
<char_identifier> ::= '
<letter> ::= = a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|
               A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z
<symbol> ::= $ | ! | # | &
<digit> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<left_paranthesis> ::= (
<right_paranthesis> ::= )
<slash> ::= /
<semicolumn> ::= ;
<sign> ::= + | -
<true> = true
<false> = false
